#!/usr/bin/env python3
"""
Generate .env from Terraform outputs and tfvars.

Usage (from repository root after terraform apply):
    cd terraform && terraform output -json > /tmp/tf_out.json && cd ..
    python3 gen-env.py
"""
import json
import re
import sys
from pathlib import Path

TFVARS   = Path("terraform/terraform.tfvars")
TF_OUT   = Path("/tmp/tf_out.json")
ENV_FILE = Path(".env")


def parse_tfvars(path: Path) -> dict:
    result = {}
    for line in path.read_text().splitlines():
        m = re.match(r'^\s*(\w+)\s*=\s*"([^"]*)"', line)
        if m:
            result[m.group(1)] = m.group(2)
    return result


def val(outputs: dict, key: str) -> str:
    return outputs.get(key, {}).get("value") or ""


TFVARS_TEMPLATE = """\
confluent_cloud_api_key    = "{key}"
confluent_cloud_api_secret = "{secret}"
cloud_region               = "us-east-1"
enable_tableflow           = true
"""


def create_tfvars(path: Path) -> None:
    print("terraform/terraform.tfvars not found. Creating it now.")
    key    = input("  Confluent Cloud API key:    ").strip()
    secret = input("  Confluent Cloud API secret: ").strip()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(TFVARS_TEMPLATE.format(key=key, secret=secret))
    print(f"  Written to {path}")
    print()
    print("Run terraform apply first, then re-run this script:")
    print("  cd terraform && terraform init && terraform apply && cd ..")
    print("  uv run python3 gen-env.py")
    sys.exit(0)


def main():
    if not TFVARS.exists():
        create_tfvars(TFVARS)
    if not TF_OUT.exists():
        print("ERROR: /tmp/tf_out.json not found. Run:")
        print("  cd terraform && terraform output -json > /tmp/tf_out.json && cd ..")
        sys.exit(1)

    tfvars  = parse_tfvars(TFVARS)
    outputs = json.loads(TF_OUT.read_text())

    cluster_id   = val(outputs, "kafka_cluster_id")
    kafka_key    = val(outputs, "kafka_api_key_id")
    kafka_secret = val(outputs, "kafka_api_key_secret")

    lines = [
        "# Generated by: python3 gen-env.py  —  do not commit",
        f"LINEAGE_BRIDGE_CONFLUENT_CLOUD_API_KEY={tfvars.get('confluent_cloud_api_key', '')}",
        f"LINEAGE_BRIDGE_CONFLUENT_CLOUD_API_SECRET={tfvars.get('confluent_cloud_api_secret', '')}",
        f'LINEAGE_BRIDGE_CLUSTER_CREDENTIALS={{"{cluster_id}":{{"api_key":"{kafka_key}","api_secret":"{kafka_secret}"}}}}',
        f"LINEAGE_BRIDGE_SCHEMA_REGISTRY_ENDPOINT={val(outputs, 'schema_registry_rest_endpoint')}",
        f"LINEAGE_BRIDGE_SCHEMA_REGISTRY_API_KEY={val(outputs, 'schema_registry_api_key_id')}",
        f"LINEAGE_BRIDGE_SCHEMA_REGISTRY_API_SECRET={val(outputs, 'schema_registry_api_key_secret')}",
        f"LINEAGE_BRIDGE_FLINK_API_KEY={val(outputs, 'flink_api_key_id')}",
        f"LINEAGE_BRIDGE_FLINK_API_SECRET={val(outputs, 'flink_api_key_secret')}",
        f"LINEAGE_BRIDGE_TABLEFLOW_API_KEY={val(outputs, 'tableflow_api_key_id')}",
        f"LINEAGE_BRIDGE_TABLEFLOW_API_SECRET={val(outputs, 'tableflow_api_key_secret')}",
        "LINEAGE_BRIDGE_LOG_LEVEL=INFO",
    ]

    ENV_FILE.write_text("\n".join(lines) + "\n")
    print(f"Written to {ENV_FILE}")


if __name__ == "__main__":
    main()
