#!/usr/bin/env python3
"""
Generate .env and patch tableflow_to_wxd.py from Terraform outputs.

Usage (from repository root after terraform apply):
    cd terraform && terraform output -json > /tmp/tf_out.json && cd ..
    uv run python3 gen-env.py
"""
import json
import re
import sys
from pathlib import Path

TFVARS           = Path("terraform/terraform.tfvars")
TF_OUT           = Path("/tmp/tf_out.json")
ENV_FILE         = Path(".env")
TF_ENV_FILE      = Path(".env.tableflow")   # separate file — not read by lineage_bridge
TABLEFLOW_SCRIPT = Path("tableflow_to_wxd.py")


def parse_tfvars(path: Path) -> dict:
    result = {}
    for line in path.read_text().splitlines():
        m = re.match(r'^\s*(\w+)\s*=\s*"([^"]*)"', line)
        if m:
            result[m.group(1)] = m.group(2)
    return result


def val(outputs: dict, key: str) -> str:
    return outputs.get(key, {}).get("value") or ""


def main():
    if not TFVARS.exists():
        print("ERROR: terraform/terraform.tfvars not found.")
        print("  Run setup first:  uv run python3 setup.py")
        sys.exit(1)
    if not TF_OUT.exists():
        print("ERROR: /tmp/tf_out.json not found. Run:")
        print("  cd terraform && terraform output -json > /tmp/tf_out.json && cd ..")
        sys.exit(1)

    tfvars  = parse_tfvars(TFVARS)
    outputs = json.loads(TF_OUT.read_text())

    cluster_id   = val(outputs, "kafka_cluster_id")
    env_id       = val(outputs, "environment_id")
    kafka_key    = val(outputs, "kafka_api_key_id")
    kafka_secret = val(outputs, "kafka_api_key_secret")

    # Tableflow uses its own dedicated key when provisioned; fall back to the
    # Cloud API key (same permissions) so the script always emits a usable value.
    tf_apikey  = val(outputs, "tableflow_api_key_id")  or tfvars.get("confluent_cloud_api_key", "")
    tf_secret  = val(outputs, "tableflow_api_key_secret") or tfvars.get("confluent_cloud_api_secret", "")

    # .env — read by lineage_bridge Settings (LINEAGE_BRIDGE_* prefix only)
    lines = [
        "# Generated by: python3 gen-env.py  —  do not commit",
        f"LINEAGE_BRIDGE_CONFLUENT_CLOUD_API_KEY={tfvars.get('confluent_cloud_api_key', '')}",
        f"LINEAGE_BRIDGE_CONFLUENT_CLOUD_API_SECRET={tfvars.get('confluent_cloud_api_secret', '')}",
        f'LINEAGE_BRIDGE_CLUSTER_CREDENTIALS={{"{cluster_id}":{{"api_key":"{kafka_key}","api_secret":"{kafka_secret}"}}}}',
        f"LINEAGE_BRIDGE_SCHEMA_REGISTRY_ENDPOINT={val(outputs, 'schema_registry_rest_endpoint')}",
        f"LINEAGE_BRIDGE_SCHEMA_REGISTRY_API_KEY={val(outputs, 'schema_registry_api_key_id')}",
        f"LINEAGE_BRIDGE_SCHEMA_REGISTRY_API_SECRET={val(outputs, 'schema_registry_api_key_secret')}",
        f"LINEAGE_BRIDGE_FLINK_API_KEY={val(outputs, 'flink_api_key_id')}",
        f"LINEAGE_BRIDGE_FLINK_API_SECRET={val(outputs, 'flink_api_key_secret')}",
        f"LINEAGE_BRIDGE_TABLEFLOW_API_KEY={val(outputs, 'tableflow_api_key_id')}",
        f"LINEAGE_BRIDGE_TABLEFLOW_API_SECRET={val(outputs, 'tableflow_api_key_secret')}",
        "LINEAGE_BRIDGE_LOG_LEVEL=INFO",
    ]

    # .env.tableflow — read only by tableflow_to_wxd.py (NOT by lineage_bridge)
    # Kept separate so lineage_bridge's Settings (extra=forbid) doesn't choke
    # on TABLEFLOW_* vars that have no LINEAGE_BRIDGE_ prefix.
    tf_lines = [
        "# Generated by: python3 gen-env.py  —  do not commit",
        "# Source this before running tableflow_to_wxd.py:",
        "#   export $(grep -v '^#' .env.tableflow | xargs)",
        f"TABLEFLOW_REGION={tfvars.get('cloud_region', 'us-east-1')}",
        f"TABLEFLOW_ORG_ID={val(outputs, 'org_id') or 'efabb4b6-83b0-4d06-943e-e7127050d10e'}",
        f"TABLEFLOW_ENV_ID={env_id}",
        f"TABLEFLOW_CLUSTER={cluster_id}",
        f"TABLEFLOW_APIKEY={tf_apikey}",
        f"TABLEFLOW_SECRET={tf_secret}",
    ]

    ENV_FILE.write_text("\n".join(lines) + "\n")
    print(f"Written to {ENV_FILE}")
    TF_ENV_FILE.write_text("\n".join(tf_lines) + "\n")
    print(f"Written to {TF_ENV_FILE}")
    patch_tableflow_script(env_id, cluster_id, tf_apikey, tf_secret)


def patch_tableflow_script(env_id: str, cluster_id: str, apikey: str, secret: str) -> None:
    """Replace FILL_IN placeholders (or stale values) in tableflow_to_wxd.py."""
    if not TABLEFLOW_SCRIPT.exists():
        print(f"  (skipping {TABLEFLOW_SCRIPT} — file not found)")
        return

    text = TABLEFLOW_SCRIPT.read_text()

    replacements = {
        r'^ENV_ID\s*=\s*"[^"]*"':        f'ENV_ID           = "{env_id}"',
        r'^CLUSTER_ID\s*=\s*"[^"]*"':    f'CLUSTER_ID       = "{cluster_id}"',
        r'^TABLEFLOW_APIKEY\s*=\s*"[^"]*"': f'TABLEFLOW_APIKEY = "{apikey}"',
        r'^TABLEFLOW_SECRET\s*=\s*"[^"]*"': f'TABLEFLOW_SECRET = "{secret}"',
    }

    for pattern, replacement in replacements.items():
        text = re.sub(pattern, replacement, text, flags=re.MULTILINE)

    TABLEFLOW_SCRIPT.write_text(text)
    print(f"Patched  {TABLEFLOW_SCRIPT}  (ENV_ID={env_id}, CLUSTER_ID={cluster_id})")


if __name__ == "__main__":
    main()
