---
- name: Output Ansible facts for localhost playbook running on
  hosts: localhost
  gather_facts: true
  tasks:

    - name: Notify user post_deploy.yaml play running
      ansible.builtin.debug:
        msg: The post_deploy.yaml play is now running.

    - name: Get listing of installed collections
      ansible.builtin.command: ansible-galaxy collection list
      register: collection_listing
      changed_when: false

    - name: Output installed collections
      ansible.builtin.debug:
        var: collection_listing.stdout

    - name: Notify dumping all known host variables
      ansible.builtin.debug:
        msg: Dumping all known host variables

    - name: Output all known host variables
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]

    - name: Notify dumping all gathered Ansible facts
      ansible.builtin.debug:
        msg: Dumping all gathered Ansible facts

    - name: Output all gathered Ansible facts
      ansible.builtin.debug:
        var: ansible_facts
